const AVERO_BLUE = "#25BBEC";
const AVERO_ORANGE = "#F39C15";
const AVERO_GREEN = "#2ECC71";
const RED = "#EA3527";

const AVERO_ICON_GREEN = "#56D1B5";
const AVERO_ICON_RED = "#E96955";
const AVERO_ICON_BLUE = "#04B1EA";
const AVERO_ICON_YELLOW = "#FEC23E";

const LIGHT_GREY = "#CCCCCC";
const MEDIUM_GREY = "#676767";

const DARK_BLUE = "#192631";

export {
  AVERO_BLUE,
  AVERO_ORANGE,
  AVERO_GREEN,
  RED,
  AVERO_ICON_GREEN,
  AVERO_ICON_RED,
  AVERO_ICON_BLUE,
  AVERO_ICON_YELLOW,
  LIGHT_GREY,
  MEDIUM_GREY,
  DARK_BLUE
};
